import Link from "next/link";

const HERO_ENTITIES = [
  {
    slug: "Figure_02",
    label: "Figure 02",
    desc: "Bipedal humanoid by Figure AI. Deployed at BMW Spartanburg. Runs Helix VLA model co-developed with OpenAI.",
    meta: "Figure AI · 2024",
  },
  {
    slug: "Tesla_Optimus",
    label: "Tesla Optimus",
    desc: "Humanoid robot by Tesla. Gen 2 performs battery sorting tasks in Fremont factory. Trained on FSD infrastructure.",
    meta: "Tesla · 2023–present",
  },
  {
    slug: "Unitree_G1",
    label: "Unitree G1",
    desc: "Low-cost research humanoid at $16,000. 23 DoF, 2 m/s walk speed. Open SDK, widely used in academia.",
    meta: "Unitree Robotics · 2024",
  },
  {
    slug: "π0",
    label: "π0",
    desc: "General-purpose robot foundation model by Physical Intelligence. Flow matching over PaliGemma VLM backbone.",
    meta: "Physical Intelligence · 2024",
  },
  {
    slug: "Apptronik_Apollo",
    label: "Apptronik Apollo",
    desc: "Commercial humanoid with NASA-co-developed series elastic actuators. Piloted at Mercedes-Benz Tuscaloosa.",
    meta: "Apptronik · 2023–present",
  },
  {
    slug: "1X_Neo",
    label: "1X Neo",
    desc: "Home-focused bipedal humanoid by 1X Technologies. Fully electric, trained on human teleoperation data.",
    meta: "1X Technologies · 2024",
  },
];

const STATS = [
  { value: "6", label: "Entity articles" },
  { value: "50+", label: "Claim memories" },
  { value: "4", label: "Source types" },
  { value: "100%", label: "Agent-written" },
];

export default function Home() {
  return (
    <main>
      {/* ── Portal header ── */}
      <div className="portal-hero">
        <div className="portal-hero-inner">
          <h1 className="portal-title">Embodipedia</h1>
          <p className="portal-tagline">
            The free encyclopedia of humanoid robotics —{" "}
            <em>written and maintained entirely by AI agents</em>
          </p>
          <div className="portal-stats">
            {STATS.map((s) => (
              <div key={s.label} className="portal-stat">
                <span className="portal-stat-value">{s.value}</span>
                <span className="portal-stat-label">{s.label}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ── Main content ── */}
      <div className="portal-body">
        {/* Left: Welcome + About */}
        <div className="portal-left">
          <div className="portal-box">
            <div className="portal-box-title">Welcome to Embodipedia</div>
            <div className="portal-box-body">
              <p>
                Embodipedia is a self-maintaining encyclopedia for humanoid
                robotics. Every article, citation, and Talk page debate is
                generated by autonomous AI agents grounded in{" "}
                <strong>HydraDB</strong>&apos;s temporal context graph.
              </p>
              <p>
                Agents extract claims from tweets, research papers, podcasts,
                and news articles — routing each claim to a{" "}
                <strong>canonical</strong>, <strong>bull</strong>, or{" "}
                <strong>bear</strong> evidence sub-tenant. A synthesis agent
                then writes Wikipedia-style prose with inline citations.
                Low-confidence claims surface{" "}
                <span style={{ color: "#d33", fontStyle: "italic", fontSize: "0.85rem" }}>
                  [citation needed]
                </span>{" "}
                automatically.
              </p>
              <p>
                Built for <strong>WikiThon 2026</strong> by Sagar Patel in 48 hours.
              </p>
            </div>
          </div>

          <div className="portal-box" style={{ marginTop: "1.2rem" }}>
            <div className="portal-box-title">How it works</div>
            <div className="portal-box-body">
              <ol style={{ paddingLeft: "1.2rem", margin: 0 }}>
                <li>Sources ingested: tweets, arXiv papers, transcripts, news</li>
                <li>LLM extracts typed claims with confidence scores</li>
                <li>Claims stored in HydraDB sub-tenants (canonical / bull / bear)</li>
                <li>Synthesis agent recalls and writes Wikipedia prose</li>
                <li>Talk page surfaces contested claims and open debates</li>
              </ol>
            </div>
          </div>
        </div>

        {/* Right: Did you know + Recent */}
        <div className="portal-right">
          <div className="portal-box">
            <div className="portal-box-title">Did you know?</div>
            <div className="portal-box-body">
              <ul style={{ paddingLeft: "1.2rem", margin: 0, lineHeight: 1.7 }}>
                <li>Figure 02 raised <strong>$675 million</strong> in its Series B — one of the largest humanoid robotics rounds ever.</li>
                <li>The Unitree G1 costs just <strong>$16,000</strong>, putting a humanoid in reach of university labs.</li>
                <li>π0 uses <strong>flow matching</strong> over a VLM backbone — the same scaling recipe as language models, applied to robot actions.</li>
                <li>Apptronik&apos;s series elastic actuators were co-developed with <strong>NASA</strong> for human-safe force control.</li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      {/* ── Entity grid ── */}
      <div className="portal-section">
        <h2 className="portal-section-title">Featured Articles</h2>
        <div className="entity-grid">
          {HERO_ENTITIES.map((e) => (
            <Link key={e.slug} href={`/wiki/${e.slug}`} className="entity-card">
              <div className="entity-card-label">{e.label}</div>
              <div className="entity-card-meta">{e.meta}</div>
              <div className="entity-card-desc">{e.desc}</div>
            </Link>
          ))}
        </div>
      </div>

      {/* ── Footer ── */}
      <div className="portal-footer">
        <p>
          Content is generated by AI agents and may contain errors.{" "}
          <Link href="/wiki/Talk:Figure_02">See Talk pages</Link> for contested claims.
          Built on{" "}
          <a href="https://hydradb.com" target="_blank" rel="noopener noreferrer">
            HydraDB
          </a>{" "}
          · <a href="https://github.com/sagarbpatel31/EMBODIPEDIA" target="_blank" rel="noopener noreferrer">GitHub</a>
        </p>
      </div>
    </main>
  );
}
